// RhettJS Global Utilities Type Definitions
// Auto-generated by TypeGenerator
// Last updated: 2025-12-18T22:58:17.740882

// ============================================================================
// Global Utilities (from globals/ directory)
// ============================================================================

declare class MessageBuffer {
    constructor(...args: any[]);
    [key: string]: any;  // Add specific methods/properties as needed
}

declare class Commander {
    constructor(...args: any[]);
    [key: string]: any;  // Add specific methods/properties as needed
}

declare const ChatHelper: any;  // Type: object

declare const globals: any;  // Type: object

