// RhettJS Core API Type Definitions
// Auto-generated by TypeGenerator using Java Reflection
// Last updated: 2025-12-18T22:58:17.729702

// ============================================================================
// Core APIs
// ============================================================================

// @ts-ignore
declare const console: {
    log(...messages: any[]): void;
    error(...messages: any[]): void;
    warn(...messages: any[]): void;
};


declare const logger: {
    info(message: string): void;
    error(message: string): void;
    error(message: string, arg1: any): void;
    warn(message: string): void;
};


declare function task(callback: () => void): void;

declare function schedule<T extends any[]>(ticks: number, callback: (...args: T) => void, ...args: T): void;

// ============================================================================
// Structure API
// ============================================================================

interface NBTFilterResult {
    value: any;
    path: (string | number)[];
    parent: any;
}

interface StructureEntity {
    blockPos: [number, number, number];
    pos: [number, number, number];
    nbt: { id: string; [key: string]: any };
}

interface StructureData {
    size: [number, number, number];
    entities?: StructureEntity[];
    [key: string]: any;
}

declare const Structure: {
    list(pool?: string): string[];
    write(name: string, data: StructureData): void;
    read(name: string): StructureData | null;
    nbt: {
        some(data: any, predicate: (value: any, path: (string | number)[], parent: any) => boolean): boolean;
        filter(data: any, predicate: (value: any, path: (string | number)[], parent: any) => boolean): NBTFilterResult[];
        find(data: any, predicate: (value: any, path: (string | number)[], parent: any) => boolean): NBTFilterResult | null;
        forEach(data: any, callback: (value: any, path: (string | number)[], parent: any) => void): void;
    };
};


// ============================================================================
// Event APIs
// ============================================================================

declare const ServerEvents: any;  // TODO: Add detailed type definitions

// ============================================================================
// Utility Script APIs (available in /rjs run)
// ============================================================================

declare const Caller: {
    sendMessage(message: string): void;
    sendSuccess(message: string): void;
    sendError(message: string): void;
    sendWarning(message: string): void;
    sendInfo(message: string): void;
    sendRaw(json: string): void;
    getName(): string;
    isPlayer(): boolean;
};

declare const Args: string[];

